package hmap;
// Generated Sep 26, 2016 6:20:53 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * FlightId generated by hbm2java
 */
public class FlightId  implements java.io.Serializable {


     private String flightNo;
     private Date flightDate;

    public FlightId() {
    }

    public FlightId(String flightNo, Date flightDate) {
       this.flightNo = flightNo;
       this.flightDate = flightDate;
    }
   
    public String getFlightNo() {
        return this.flightNo;
    }
    
    public void setFlightNo(String flightNo) {
        this.flightNo = flightNo;
    }
    public Date getFlightDate() {
        return this.flightDate;
    }
    
    public void setFlightDate(Date flightDate) {
        this.flightDate = flightDate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FlightId) ) return false;
		 FlightId castOther = ( FlightId ) other; 
         
		 return ( (this.getFlightNo()==castOther.getFlightNo()) || ( this.getFlightNo()!=null && castOther.getFlightNo()!=null && this.getFlightNo().equals(castOther.getFlightNo()) ) )
 && ( (this.getFlightDate()==castOther.getFlightDate()) || ( this.getFlightDate()!=null && castOther.getFlightDate()!=null && this.getFlightDate().equals(castOther.getFlightDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getFlightNo() == null ? 0 : this.getFlightNo().hashCode() );
         result = 37 * result + ( getFlightDate() == null ? 0 : this.getFlightDate().hashCode() );
         return result;
   }   


}


