package hmap;
// Generated Sep 26, 2016 6:20:53 PM by Hibernate Tools 4.3.1



/**
 * Ogauser generated by hbm2java
 */
public class Ogauser  implements java.io.Serializable {


     private String username;
     private String commonname;
     private String agencyname;
     private String email;
     private String password;
     private String agencycode;
     private String phone;

    public Ogauser() {
    }

	
    public Ogauser(String username, String commonname, String agencyname, String password) {
        this.username = username;
        this.commonname = commonname;
        this.agencyname = agencyname;
        this.password = password;
    }
    public Ogauser(String username, String commonname, String agencyname, String email, String password, String agencycode, String phone) {
       this.username = username;
       this.commonname = commonname;
       this.agencyname = agencyname;
       this.email = email;
       this.password = password;
       this.agencycode = agencycode;
       this.phone = phone;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getCommonname() {
        return this.commonname;
    }
    
    public void setCommonname(String commonname) {
        this.commonname = commonname;
    }
    public String getAgencyname() {
        return this.agencyname;
    }
    
    public void setAgencyname(String agencyname) {
        this.agencyname = agencyname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getAgencycode() {
        return this.agencycode;
    }
    
    public void setAgencycode(String agencycode) {
        this.agencycode = agencycode;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }




}


