package hmap;
// Generated Sep 26, 2016 6:20:53 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PassengerId generated by hbm2java
 */
public class PassengerId  implements java.io.Serializable {


     private String flightNo;
     private Date flightDate;
     private String travelDocNumber;

    public PassengerId() {
    }

    public PassengerId(String flightNo, Date flightDate, String travelDocNumber) {
       this.flightNo = flightNo;
       this.flightDate = flightDate;
       this.travelDocNumber = travelDocNumber;
    }
   
    public String getFlightNo() {
        return this.flightNo;
    }
    
    public void setFlightNo(String flightNo) {
        this.flightNo = flightNo;
    }
    public Date getFlightDate() {
        return this.flightDate;
    }
    
    public void setFlightDate(Date flightDate) {
        this.flightDate = flightDate;
    }
    public String getTravelDocNumber() {
        return this.travelDocNumber;
    }
    
    public void setTravelDocNumber(String travelDocNumber) {
        this.travelDocNumber = travelDocNumber;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PassengerId) ) return false;
		 PassengerId castOther = ( PassengerId ) other; 
         
		 return ( (this.getFlightNo()==castOther.getFlightNo()) || ( this.getFlightNo()!=null && castOther.getFlightNo()!=null && this.getFlightNo().equals(castOther.getFlightNo()) ) )
 && ( (this.getFlightDate()==castOther.getFlightDate()) || ( this.getFlightDate()!=null && castOther.getFlightDate()!=null && this.getFlightDate().equals(castOther.getFlightDate()) ) )
 && ( (this.getTravelDocNumber()==castOther.getTravelDocNumber()) || ( this.getTravelDocNumber()!=null && castOther.getTravelDocNumber()!=null && this.getTravelDocNumber().equals(castOther.getTravelDocNumber()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getFlightNo() == null ? 0 : this.getFlightNo().hashCode() );
         result = 37 * result + ( getFlightDate() == null ? 0 : this.getFlightDate().hashCode() );
         result = 37 * result + ( getTravelDocNumber() == null ? 0 : this.getTravelDocNumber().hashCode() );
         return result;
   }   


}


